name: suvarnabhumi_parking_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  cloud_functions: ^5.3.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  barcode: ^2.2.8
  excel: ^4.0.2
  universal_html: ^2.2.4
  pdf: ^3.10.8
  printing: ^5.12.0
  # ----------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # --- เพิ่มบรรทัดนี้เข้าไปใต้ assets เดิม ---
    - assets/fonts/
    # ----------------------------------------